# Generated by Django 4.0.3 on 2022-03-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'managed': True, 'ordering': ['author', '-created_on'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
