# Generated by Django 4.0.3 on 2022-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotemodel',
            name='note',
            field=models.TextField(max_length=250, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='note',
            field=models.TextField(max_length=250, verbose_name='Note'),
        ),
    ]
