# Generated by Django 4.0.3 on 2022-03-13 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0004_rename_concretetype_concreteitems_and_more'),
        ('clients', '0003_alter_lot_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='purchase order')),
                ('etotal', models.SmallIntegerField(verbose_name='estimated total')),
                ('atotal', models.SmallIntegerField(blank=True, null=True, verbose_name='actual total')),
                ('qordered', models.SmallIntegerField(verbose_name='total ordered')),
                ('mix', models.CharField(choices=[('rich', 'rich'), ('standard', 'standard'), ('medium', 'medium'), ('lean', 'lean')], default='standard', max_length=10, verbose_name='mix')),
                ('slump', models.CharField(max_length=6, verbose_name='slump')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Order Notes')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corders_accepted', to=settings.AUTH_USER_MODEL, verbose_name='dispatcher')),
                ('lots', models.ManyToManyField(related_name='orders', to='clients.lot', verbose_name='lots')),
            ],
            options={
                'verbose_name': 'Concrete Order',
                'verbose_name_plural': 'Concrete Orders',
                'db_table': 'orders_concrete',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PumpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.CharField(blank=True, max_length=50, null=True, verbose_name='crew pouring')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='concrete time')),
                ('temp', models.CharField(blank=True, choices=[(None, None), ('high', 'high'), ('low', 'low')], default=None, max_length=4, null=True, verbose_name='temperature')),
                ('precip', models.CharField(blank=True, choices=[(None, None), ('rain', 'rain'), ('snow', 'snow')], default=None, max_length=5, null=True, verbose_name='inclimate weather')),
                ('progress', models.CharField(choices=[('will call', 'will call'), ('canceled', 'canceled'), ('in_progress', 'in_progress'), ('released', 'released'), ('complete', 'complete')], max_length=15, verbose_name='pour progress')),
            ],
            options={
                'verbose_name': 'Pump Info',
                'db_table': 'orders_concrete_pumpinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FootingsOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='concrete.concreteorder', verbose_name='order')),
                ('garage', models.CharField(choices=[("4'", "4'"), ("8'", "8'"), ("9'", "9'")], default="8'", max_length=4, verbose_name='garage')),
                ('wea', models.CharField(max_length=50, verbose_name='walkout egress area')),
            ],
            options={
                'verbose_name': 'Footings Order',
                'verbose_name_plural': 'Footings Orders',
                'db_table': 'orders_concrete_footings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WallOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='concrete.concreteorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Wall Order',
                'verbose_name_plural': 'Wall Orders',
                'db_table': 'orders_concrete_walls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalWallOrder',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concrete.concreteorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'historical Wall Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFootingsOrder',
            fields=[
                ('garage', models.CharField(choices=[("4'", "4'"), ("8'", "8'"), ("9'", "9'")], default="8'", max_length=4, verbose_name='garage')),
                ('wea', models.CharField(max_length=50, verbose_name='walkout egress area')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concrete.concreteorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'historical Footings Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFlatworkOrder',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concrete.concreteorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'historical Flatwork Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConcreteOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('po', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='purchase order')),
                ('etotal', models.SmallIntegerField(verbose_name='estimated total')),
                ('atotal', models.SmallIntegerField(blank=True, null=True, verbose_name='actual total')),
                ('qordered', models.SmallIntegerField(verbose_name='total ordered')),
                ('mix', models.CharField(choices=[('rich', 'rich'), ('standard', 'standard'), ('medium', 'medium'), ('lean', 'lean')], default='standard', max_length=10, verbose_name='mix')),
                ('slump', models.CharField(max_length=6, verbose_name='slump')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Order Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dispatcher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dispatcher')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pinfo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concrete.pumpinfo', verbose_name='pump info')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical Concrete Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='concreteorder',
            name='pinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concrete.pumpinfo', verbose_name='pump info'),
        ),
        migrations.AddField(
            model_name='concreteorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.CreateModel(
            name='FlatworkOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='concrete.concreteorder', verbose_name='order')),
                ('items', models.ManyToManyField(related_name='concrete_orders', to='suppliers.concreteitems', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Flatwork Order',
                'verbose_name_plural': 'Flatwork Orders',
                'db_table': 'orders_concrete_flatwork',
                'managed': True,
            },
        ),
    ]
