# Generated by Django 4.0.3 on 2022-03-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix', models.CharField(choices=[('rich', 'rich'), ('standard', 'standard'), ('medium', 'medium'), ('lean', 'lean')], default='standard', max_length=10, verbose_name='mix')),
                ('slump', models.CharField(max_length=6, verbose_name='slump')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notemodel', verbose_name='note')),
            ],
            options={
                'verbose_name': 'Concrete Type',
                'verbose_name_plural': 'Concrete Types',
                'db_table': 'concrete_types',
                'managed': True,
            },
        ),
    ]
