# Generated by Django 4.0.3 on 2022-03-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concreteorder',
            table='concrete_orders',
        ),
    ]
