# Generated by Django 4.0.3 on 2022-03-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatworkorder',
            options={'managed': True, 'verbose_name': 'Wall Order', 'verbose_name_plural': 'Wall Orders'},
        ),
        migrations.AlterModelOptions(
            name='historicalflatworkorder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Wall Order'},
        ),
        migrations.AlterModelTable(
            name='flatworkorder',
            table='orders_concrete_flatwork',
        ),
        migrations.AlterModelTable(
            name='footingsorder',
            table='orders_concrete_footings',
        ),
    ]
