# Generated by Django 4.0.3 on 2022-03-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_concreteorder_inspection_and_more'),
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretetype',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.concreteorder', verbose_name='concrete orders'),
            preserve_default=False,
        ),
    ]
