# Generated by Django 4.0.3 on 2022-03-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpScheduleNotes',
            fields=[
                ('notemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notemodel')),
            ],
            options={
                'verbose_name': 'pump schedule note',
                'verbose_name_plural': 'pump schedule notes',
                'db_table': 'concrete_pump_schedule_notes',
                'managed': True,
            },
            bases=('core.notemodel',),
        ),
        migrations.RenameModel(
            old_name='WeatherNotes',
            new_name='InclimateWeatherNotes',
        ),
        migrations.AlterModelOptions(
            name='historicalpumpschedule',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical concrete pump schedule'},
        ),
        migrations.AlterModelOptions(
            name='pumpschedule',
            options={'managed': True, 'verbose_name': 'concrete pump schedule'},
        ),
        migrations.AlterModelTable(
            name='pumpschedule',
            table='concrete_pump_schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleNotes',
        ),
        migrations.AddField(
            model_name='pumpschedulenotes',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_schedule_notes', to='concrete.pumpschedule', verbose_name='pump scheduled'),
        ),
    ]
