# Generated by Django 4.0.3 on 2022-03-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_pumpschedulenotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatworkOrder',
            fields=[
            ],
            options={
                'verbose_name': 'flatwork order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('concrete.concreteorder',),
        ),
        migrations.CreateModel(
            name='FootingsOrder',
            fields=[
            ],
            options={
                'verbose_name': 'footings order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('concrete.concreteorder',),
        ),
        migrations.CreateModel(
            name='WallOrder',
            fields=[
            ],
            options={
                'verbose_name': 'wall order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('concrete.concreteorder',),
        ),
        migrations.AddField(
            model_name='historicalpumpschedule',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concrete.concreteorder', verbose_name='concrete order'),
        ),
        migrations.AddField(
            model_name='pumpschedule',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='concrete.concreteorder', verbose_name='concrete order'),
            preserve_default=False,
        ),
    ]
