# Generated by Django 4.0.3 on 2022-03-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_pumpinfo_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concreteorder',
            old_name='order_notes',
            new_name='onotes',
        ),
        migrations.RenameField(
            model_name='historicalconcreteorder',
            old_name='order_notes',
            new_name='onotes',
        ),
        migrations.RemoveField(
            model_name='concreteorder',
            name='pinfo',
        ),
        migrations.RemoveField(
            model_name='historicalconcreteorder',
            name='pinfo',
        ),
        migrations.AddField(
            model_name='pumpinfo',
            name='pnotes',
            field=models.TextField(blank=True, null=True, verbose_name='Order Notes'),
        ),
    ]
