# Generated by Django 4.0.3 on 2022-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0003_flatworkorder_footingsorder_wallorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatworkitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='item description'),
        ),
    ]
