# Generated by Django 4.0.3 on 2022-03-31 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_historicalinspectionmodel_note_and_more'),
        ('concrete', '0004_alter_concretetype_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretetype',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ctypes', to='orders.concreteorder', verbose_name='concrete orders'),
        ),
    ]
