# Generated by Django 4.0.2 on 2022-02-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldr', models.CharField(max_length=50, verbose_name='Builder')),
                ('job_site', models.CharField(max_length=50, verbose_name='Job Site')),
                ('lot', models.PositiveSmallIntegerField(verbose_name='Lot Number')),
                ('caller', models.CharField(max_length=50, verbose_name='Caller')),
                ('r_loads', models.PositiveIntegerField(verbose_name='Loads Requested')),
                ('d_loads', models.PositiveIntegerField(blank=True, verbose_name='Loads Delivered')),
                ('stone', models.CharField(max_length=50, verbose_name='Stone Type')),
                ('bsdt', models.CharField(max_length=50, verbose_name='B/S D/T')),
                ('supplier', models.CharField(max_length=50, verbose_name='Supplier')),
                ('driver', models.CharField(blank=True, max_length=50, verbose_name='Driver')),
                ('n_date', models.DateField(verbose_name='Date Needed')),
                ('d_date', models.DateField(blank=True, verbose_name='Date Delivered')),
                ('priority', models.CharField(max_length=50, verbose_name='Priority')),
                ('po', models.PositiveIntegerField(verbose_name='P.O. Number')),
            ],
            options={
                'verbose_name': 'Gravel Order',
                'verbose_name_plural': 'Gravel Orders',
                'db_table': 'g_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalGravelOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bldr', models.CharField(max_length=50, verbose_name='Builder')),
                ('job_site', models.CharField(max_length=50, verbose_name='Job Site')),
                ('lot', models.PositiveSmallIntegerField(verbose_name='Lot Number')),
                ('caller', models.CharField(max_length=50, verbose_name='Caller')),
                ('r_loads', models.PositiveIntegerField(verbose_name='Loads Requested')),
                ('d_loads', models.PositiveIntegerField(blank=True, verbose_name='Loads Delivered')),
                ('stone', models.CharField(max_length=50, verbose_name='Stone Type')),
                ('bsdt', models.CharField(max_length=50, verbose_name='B/S D/T')),
                ('supplier', models.CharField(max_length=50, verbose_name='Supplier')),
                ('driver', models.CharField(blank=True, max_length=50, verbose_name='Driver')),
                ('n_date', models.DateField(verbose_name='Date Needed')),
                ('d_date', models.DateField(blank=True, verbose_name='Date Delivered')),
                ('priority', models.CharField(max_length=50, verbose_name='Priority')),
                ('po', models.PositiveIntegerField(verbose_name='P.O. Number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gravel Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
