# Generated by Django 4.0.2 on 2022-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravelorder',
            name='d_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Delivered'),
        ),
        migrations.AlterField(
            model_name='gravelorder',
            name='d_loads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Loads Delivered'),
        ),
        migrations.AlterField(
            model_name='gravelorder',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='historicalgravelorder',
            name='d_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Delivered'),
        ),
        migrations.AlterField(
            model_name='historicalgravelorder',
            name='d_loads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Loads Delivered'),
        ),
        migrations.AlterField(
            model_name='historicalgravelorder',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver'),
        ),
    ]
