# Generated by Django 4.0.2 on 2022-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteorder',
            name='ctype',
            field=models.CharField(choices=[('mix', 'mix'), ('slmp', 'slmp')], max_length=4, verbose_name='Mix/Slump'),
        ),
        migrations.AlterField(
            model_name='historicalconcreteorder',
            name='ctype',
            field=models.CharField(choices=[('mix', 'mix'), ('slmp', 'slmp')], max_length=4, verbose_name='Mix/Slump'),
        ),
    ]
