# Generated by Django 4.0.2 on 2022-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_alter_concreteorder_ctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteorder',
            name='garage',
            field=models.CharField(blank=True, default='n/a', help_text='only for footings', max_length=3, null=True, verbose_name='Garage Height'),
        ),
        migrations.AddField(
            model_name='concreteorder',
            name='wea',
            field=models.CharField(blank=True, default='n/a', help_text='only for footings', max_length=50, null=True, verbose_name='Walkout Egress Area'),
        ),
        migrations.AddField(
            model_name='historicalconcreteorder',
            name='garage',
            field=models.CharField(blank=True, default='n/a', help_text='only for footings', max_length=3, null=True, verbose_name='Garage Height'),
        ),
        migrations.AddField(
            model_name='historicalconcreteorder',
            name='wea',
            field=models.CharField(blank=True, default='n/a', help_text='only for footings', max_length=50, null=True, verbose_name='Walkout Egress Area'),
        ),
    ]
