# Generated by Django 4.0.2 on 2022-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="staff status"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="staff status"),
        ),
    ]
