# Generated by Django 4.0.3 on 2022-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active builder'),
        ),
        migrations.AddField(
            model_name='historicalbuilder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active builder'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalbuilder',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='name'),
        ),
    ]
