# Generated by Django 4.0.3 on 2022-03-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buildermodel',
            managers=[
            ],
        ),
    ]
