# Generated by Django 4.0.3 on 2022-03-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_builder_is_active_historicalbuilder_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_lots', to='clients.builder', verbose_name='builder'),
        ),
    ]
