# Generated by Django 4.0.3 on 2022-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_buildermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalbuildermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
