# Generated by Django 4.0.3 on 2022-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='incw',
            field=models.CharField(choices=[('none', 'none'), ('rain', 'rain'), ('snow', 'snow')], default='none', max_length=4, verbose_name='Inclimate Weather'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='otype',
            field=models.CharField(choices=[('flatwork', 'flatwork'), ('footings', 'footings'), ('walls', 'walls')], max_length=8, verbose_name='Pour Type'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='temp',
            field=models.CharField(choices=[('none', 'average'), ('low', 'low'), ('high', 'high')], default='none', max_length=4, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='incw',
            field=models.CharField(choices=[('none', 'none'), ('rain', 'rain'), ('snow', 'snow')], default='none', max_length=4, verbose_name='Inclimate Weather'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='otype',
            field=models.CharField(choices=[('flatwork', 'flatwork'), ('footings', 'footings'), ('walls', 'walls')], max_length=8, verbose_name='Pour Type'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='temp',
            field=models.CharField(choices=[('none', 'average'), ('low', 'low'), ('high', 'high')], default='none', max_length=4, verbose_name='Temperature'),
        ),
    ]
