# Generated by Django 4.0.2 on 2022-03-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_historicalconcretenote_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='garage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='only for footings', null=True, verbose_name='Garage Height (ft)'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='wea',
            field=models.PositiveSmallIntegerField(blank=True, help_text='only for footings', null=True, verbose_name='Walkout Egress Area (ft)'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='garage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='only for footings', null=True, verbose_name='Garage Height (ft)'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='wea',
            field=models.PositiveSmallIntegerField(blank=True, help_text='only for footings', null=True, verbose_name='Walkout Egress Area (ft)'),
        ),
    ]
