# Generated by Django 4.0.2 on 2022-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_concrete_garage_alter_concrete_wea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='pinfo',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Pump Info'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='pinfo',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Pump Info'),
        ),
    ]
