# Generated by Django 4.0.3 on 2022-03-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Concrete Type')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Concrete Type',
                'verbose_name_plural': 'Concrete Types',
                'db_table': 'concrete_types',
                'managed': True,
            },
        ),
    ]
