# Generated by Django 4.0.3 on 2022-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_concretetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stonetype',
            name='item_type',
            field=models.CharField(choices=[('Gravel', 'Gravel'), ('Concrete', 'Concrete')], default='Gravel', max_length=10),
            preserve_default=False,
        ),
    ]
