# Generated by Django 4.0.3 on 2022-03-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_stonetype_item_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcreteType',
            new_name='ConcreteItems',
        ),
        migrations.AlterModelTable(
            name='concreteitems',
            table='suppliers_concreteitems',
        ),
        migrations.AlterModelTable(
            name='stonetype',
            table='suppliers_gravelitems',
        ),
    ]
