# Generated by Django 4.0.4 on 2022-04-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concreteorderschedule',
            options={'managed': True, 'verbose_name': 'Concrete Delivery'},
        ),
        migrations.AlterModelOptions(
            name='historicalconcreteorderschedule',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Concrete Delivery'},
        ),
        migrations.AlterModelTable(
            name='concreteorderschedule',
            table='concrete_delivery_schedule',
        ),
    ]
