# Generated by Django 4.0.3 on 2022-03-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveldeliveryschedule',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Drivers'}, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
        migrations.AlterField(
            model_name='historicalgraveldeliveryschedule',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
    ]
