# Generated by Django 4.0.3 on 2022-03-26 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_notemodel_options'),
        ('schedules', '0002_alter_graveldeliveryschedule_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpumpschedule',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
        migrations.AlterField(
            model_name='pumpschedule',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Drivers'}, on_delete=django.db.models.deletion.PROTECT, related_name='pump_schedules', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
        migrations.CreateModel(
            name='InclimateWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=50, verbose_name='temperature')),
                ('precip', models.CharField(max_length=50, verbose_name='precipitation')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notemodel', verbose_name='')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.pumpschedule', verbose_name='inclimate weather')),
            ],
            options={
                'verbose_name': 'inclimate weather report',
                'verbose_name_plural': 'inclimate weather reports',
                'db_table': 'schedules_concrete_schedule_weather',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalInclimateWeather',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('temp', models.CharField(max_length=50, verbose_name='temperature')),
                ('precip', models.CharField(max_length=50, verbose_name='precipitation')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.notemodel', verbose_name='')),
                ('pump', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedules.pumpschedule', verbose_name='inclimate weather')),
            ],
            options={
                'verbose_name': 'historical inclimate weather report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
