# Generated by Django 4.0.3 on 2022-03-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notemodel_options'),
        ('schedules', '0003_alter_historicalpumpschedule_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpScheduleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_notes', to='core.notemodel', verbose_name='pump note')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_schedule', to='schedules.pumpschedule', verbose_name='pump')),
            ],
            options={
                'verbose_name': 'Pump Schedule Note',
                'verbose_name_plural': 'Pump Schedule Notes',
                'db_table': 'schedules_pump_schedule_notes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GravelDeliveryScheduleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_delivery', to='schedules.graveldeliveryschedule', verbose_name='pump')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_delivery_notes', to='core.notemodel', verbose_name='pump note')),
            ],
            options={
                'verbose_name': 'Gravel Delivery Schedule Note',
                'verbose_name_plural': 'Gravel Delivery Schedule Notes',
                'db_table': 'schedules_gravel_delivery_schedule_notes',
                'managed': True,
            },
        ),
    ]
