# Generated by Django 4.0.3 on 2022-03-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_graveldeliveryschedulenote_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graveldeliveryschedule',
            name='note',
        ),
        migrations.RemoveField(
            model_name='historicalgraveldeliveryschedule',
            name='note',
        ),
    ]
