# Generated by Django 4.0.3 on 2022-03-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_remove_graveldeliveryschedule_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graveldeliveryschedulenote',
            options={'managed': True, 'verbose_name': 'Gravel Delivery Note', 'verbose_name_plural': 'Gravel Delivery Notes'},
        ),
    ]
