# Generated by Django 4.0.3 on 2022-03-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notemodel_options'),
        ('schedules', '0007_alter_graveldeliveryschedulenote_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinclimateweather',
            name='note',
        ),
        migrations.RemoveField(
            model_name='inclimateweather',
            name='note',
        ),
        migrations.AlterField(
            model_name='historicalinclimateweather',
            name='pump',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedules.pumpschedule', verbose_name='pump schedule'),
        ),
        migrations.AlterField(
            model_name='inclimateweather',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_delay', to='schedules.pumpschedule', verbose_name='pump schedule'),
        ),
        migrations.CreateModel(
            name='InclimateWeatherNote',
            fields=[
                ('notemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notemodel')),
                ('delay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.inclimateweather', verbose_name='delay')),
            ],
            bases=('core.notemodel',),
        ),
    ]
