# Generated by Django 4.0.3 on 2022-03-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0008_remove_historicalinclimateweather_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graveldeliveryschedule',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Check if the supplier is responsible for delivering the order', verbose_name='supplier delivers'),
        ),
        migrations.AddField(
            model_name='historicalgraveldeliveryschedule',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Check if the supplier is responsible for delivering the order', verbose_name='supplier delivers'),
        ),
        migrations.AlterField(
            model_name='graveldeliveryschedule',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
    ]
