# Generated by Django 4.0.3 on 2022-03-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_gravelorder_builder_and_more'),
        ('schedules', '0009_graveldeliveryschedule_supplier_delivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpumpschedule',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Check if the supplier is responsible for delivering the order', verbose_name='supplier delivers'),
        ),
        migrations.AddField(
            model_name='pumpschedule',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Check if the supplier is responsible for delivering the order', verbose_name='supplier delivers'),
        ),
        migrations.AlterField(
            model_name='graveldeliveryschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravel_deliveries', to='orders.gravelorder', verbose_name='order'),
        ),
    ]
