# Generated by Django 4.0.3 on 2022-03-27 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0010_historicalpumpschedule_supplier_delivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpschedule',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pump_schedules', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver'),
        ),
    ]
