# Generated by Django 4.0.3 on 2022-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_alter_graveldeliveryschedule_order'),
        ('schedules', '0011_alter_pumpschedule_driver'),
    ]

    operations = [
    ]
