# Generated by Django 4.0.3 on 2022-04-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_alter_pumpschedulenote_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveldeliveryschedulenote',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_delivery_notes', to='schedules.graveldeliveryschedule', verbose_name='pump'),
        ),
    ]
