# Generated by Django 4.0.3 on 2022-04-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_alter_graveldeliveryschedulenote_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpumpschedule',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pump'},
        ),
        migrations.AlterModelOptions(
            name='pumpschedule',
            options={'managed': True, 'verbose_name': 'pump'},
        ),
    ]
