# Generated by Django 4.0.3 on 2022-03-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='job_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_orders', to='jobs.jobsite', verbose_name='Subdivision'),
        ),
        migrations.AlterField(
            model_name='gravel',
            name='job_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_orders', to='jobs.jobsite', verbose_name='Subdivision'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='job_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobs.jobsite', verbose_name='Subdivision'),
        ),
        migrations.AlterField(
            model_name='historicalgravel',
            name='job_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobs.jobsite', verbose_name='Subdivision'),
        ),
    ]
