# Generated by Django 4.0.3 on 2022-03-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_buildermodel_managers'),
        ('sites', '0002_alter_historicalsitemodel_project_manager_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gravelorder',
            old_name='lot',
            new_name='lots',
        ),
        migrations.RenameField(
            model_name='historicalgravelorder',
            old_name='lot',
            new_name='lots',
        ),
        migrations.AddField(
            model_name='gravelorder',
            name='builder',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='builder_gravel_orders', to='clients.buildermodel', verbose_name='builders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gravelorder',
            name='site',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_gravel_deliveries', to='sites.sitemodel', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='historicalgravelorder',
            name='builder',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.buildermodel', verbose_name='builders'),
        ),
        migrations.AddField(
            model_name='historicalgravelorder',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.sitemodel', verbose_name='site'),
        ),
    ]
