# Generated by Django 4.0.3 on 2022-03-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalconcrete',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.RemoveField(
            model_name='concrete',
            name='notes',
        ),
        migrations.AddField(
            model_name='concrete',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='notes',
        ),
        migrations.AddField(
            model_name='gravel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.DeleteModel(
            name='HistoricalOrderNotes',
        ),
        migrations.DeleteModel(
            name='OrderNotes',
        ),
    ]
