# Generated by Django 4.0.4 on 2022-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravelorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalgravelorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
