# Generated by Django 4.0.3 on 2022-03-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_concretetype'),
        ('orders', '0002_alter_concrete_job_site_alter_gravel_job_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concrete',
            name='item',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalconcrete',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='item',
        ),
        migrations.AddField(
            model_name='concrete',
            name='ptype',
            field=models.CharField(choices=[('mix', 'mix'), ('slump', 'slump')], default='mix', max_length=5, verbose_name='Mix/Slump'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalconcrete',
            name='ptype',
            field=models.CharField(choices=[('mix', 'mix'), ('slump', 'slump')], default='mix', max_length=5, verbose_name='Mix/Slump'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concrete',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.concretetype', verbose_name='Concrete Type'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.concretetype', verbose_name='Concrete Type'),
        ),
    ]
