# Generated by Django 4.0.3 on 2022-03-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalconcrete_notes_historicalgravel_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravel',
            name='d_date',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='n_date',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='d_date',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='n_date',
        ),
    ]
