# Generated by Django 4.0.3 on 2022-03-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_lot_gravelorder_lots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteorder',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.inspectionmodel', verbose_name='inspection'),
        ),
        migrations.AddField(
            model_name='historicalconcreteorder',
            name='inspection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.inspectionmodel', verbose_name='inspection'),
        ),
    ]
