# Generated by Django 4.0.3 on 2022-03-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_concretetype'),
        ('orders', '0003_remove_concrete_item_remove_gravel_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concrete_orders', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
