# Generated by Django 4.0.3 on 2022-03-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_concreteorder_inspection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatworkorderitems',
            options={'managed': True, 'verbose_name': 'flatwork item'},
        ),
        migrations.RemoveField(
            model_name='concreteorder',
            name='cinfo',
        ),
        migrations.RemoveField(
            model_name='historicalconcreteorder',
            name='cinfo',
        ),
        migrations.AlterField(
            model_name='concreteorder',
            name='dispatcher',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Dispatchers'}, on_delete=django.db.models.deletion.PROTECT, related_name='corders_accepted', to=settings.AUTH_USER_MODEL, verbose_name='dispatcher'),
        ),
        migrations.AlterField(
            model_name='historicalconcreteorder',
            name='dispatcher',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'Dispatchers'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dispatcher'),
        ),
    ]
