# Generated by Django 4.0.4 on 2022-04-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_concreteorder_qordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_order_notes', to='orders.concreteorder', verbose_name='concrete order'),
        ),
    ]
