# Generated by Django 4.0.3 on 2022-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_concrete_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravel',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='crew',
        ),
        migrations.AlterField(
            model_name='concrete',
            name='atot',
            field=models.PositiveIntegerField(default=0, verbose_name='Actual Total'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='etot',
            field=models.PositiveIntegerField(default=0, help_text='leave blank if same as quantity ordered', verbose_name='Estimated Total'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='progress',
            field=models.CharField(choices=[('will call', 'will call'), ('scheduled', 'scheduled'), ('canceled', 'canceled'), ('released', 'released'), ('complete', 'complete')], default='will call', max_length=10, verbose_name='Order Progress'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='qord',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Ordered'),
        ),
        migrations.AlterField(
            model_name='gravel',
            name='progress',
            field=models.CharField(choices=[('will call', 'will call'), ('scheduled', 'scheduled'), ('canceled', 'canceled'), ('released', 'released'), ('complete', 'complete')], default='will call', max_length=10, verbose_name='Order Progress'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='atot',
            field=models.PositiveIntegerField(default=0, verbose_name='Actual Total'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='etot',
            field=models.PositiveIntegerField(default=0, help_text='leave blank if same as quantity ordered', verbose_name='Estimated Total'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='progress',
            field=models.CharField(choices=[('will call', 'will call'), ('scheduled', 'scheduled'), ('canceled', 'canceled'), ('released', 'released'), ('complete', 'complete')], default='will call', max_length=10, verbose_name='Order Progress'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='qord',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Ordered'),
        ),
        migrations.AlterField(
            model_name='historicalgravel',
            name='progress',
            field=models.CharField(choices=[('will call', 'will call'), ('scheduled', 'scheduled'), ('canceled', 'canceled'), ('released', 'released'), ('complete', 'complete')], default='will call', max_length=10, verbose_name='Order Progress'),
        ),
    ]
