# Generated by Django 4.0.3 on 2022-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_concrete_odate_alter_gravel_odate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='odate',
            field=models.DateField(auto_now=True, verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='gravel',
            name='odate',
            field=models.DateField(auto_now=True, verbose_name='Date Ordered'),
        ),
    ]
