# Generated by Django 4.0.3 on 2022-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_flatworkorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteorder',
            name='date_needed',
            field=models.DateField(blank=True, null=True, verbose_name='date needed'),
        ),
        migrations.AlterField(
            model_name='historicalconcreteorder',
            name='date_needed',
            field=models.DateField(blank=True, null=True, verbose_name='date needed'),
        ),
    ]
