# Generated by Django 4.0.3 on 2022-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_gravel_crew_remove_historicalgravel_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='etot',
            field=models.PositiveIntegerField(help_text='leave blank if same as quantity ordered', verbose_name='Estimated Total'),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='qtype',
            field=models.CharField(choices=[('Large Loads', (('cu yd', 'cu yd'), ('sqft', 'sqft'))), ('Regular Loads', (('lbs', 'lbs'), ('bags', 'bags')))], default='sqft', max_length=5, verbose_name='Quantity Type'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='etot',
            field=models.PositiveIntegerField(help_text='leave blank if same as quantity ordered', verbose_name='Estimated Total'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='qtype',
            field=models.CharField(choices=[('Large Loads', (('cu yd', 'cu yd'), ('sqft', 'sqft'))), ('Regular Loads', (('lbs', 'lbs'), ('bags', 'bags')))], default='sqft', max_length=5, verbose_name='Quantity Type'),
        ),
    ]
