# Generated by Django 4.0.4 on 2022-04-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_concreteordernote_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix', models.CharField(choices=[('rich', 'rich'), ('standard', 'standard'), ('medium', 'medium'), ('lean', 'lean')], default='standard', max_length=10, verbose_name='mix')),
                ('slump', models.CharField(max_length=6, verbose_name='slump')),
                ('note', models.TextField(blank=True, max_length=250, null=True, verbose_name='note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_supplies', to='orders.concreteorder', verbose_name='concrete orders')),
            ],
            options={
                'verbose_name': 'Concrete Type',
                'verbose_name_plural': 'Concrete Types',
                'db_table': 'supplies_concrete_types',
                'managed': True,
            },
        ),
    ]
