# Generated by Django 4.0.3 on 2022-03-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_concrete_odate_alter_gravel_odate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='odate',
            field=models.DateField(verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='gravel',
            name='odate',
            field=models.DateField(verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='odate',
            field=models.DateField(verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='historicalgravel',
            name='odate',
            field=models.DateField(verbose_name='Date Ordered'),
        ),
    ]
