# Generated by Django 4.0.3 on 2022-03-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_concrete_odate_alter_gravel_odate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravel',
            name='dloads',
            field=models.PositiveIntegerField(default=15, verbose_name='Loads Delivered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gravel',
            name='rloads',
            field=models.PositiveIntegerField(default=15, verbose_name='Loads Requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='dloads',
            field=models.PositiveIntegerField(default=15, verbose_name='Loads Delivered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='rloads',
            field=models.PositiveIntegerField(default=15, verbose_name='Loads Requested'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concrete',
            name='qtype',
            field=models.CharField(choices=[('Large Loads', (('cu yd', 'cu yd'), ('sqft', 'sqft'))), ('lbs', 'lbs'), ('bags', 'bags')], default='sqft', max_length=5, verbose_name='Quantity Type'),
        ),
        migrations.AlterField(
            model_name='historicalconcrete',
            name='qtype',
            field=models.CharField(choices=[('Large Loads', (('cu yd', 'cu yd'), ('sqft', 'sqft'))), ('lbs', 'lbs'), ('bags', 'bags')], default='sqft', max_length=5, verbose_name='Quantity Type'),
        ),
    ]
