# Generated by Django 4.0.4 on 2022-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_concretetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteorder',
            name='needs_pump',
            field=models.BooleanField(default=False, verbose_name='pump required?'),
        ),
        migrations.AddField(
            model_name='historicalconcreteorder',
            name='needs_pump',
            field=models.BooleanField(default=False, verbose_name='pump required?'),
        ),
    ]
