# Generated by Django 4.0.3 on 2022-03-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('orders', '0007_gravel_dloads_gravel_rloads_historicalgravel_dloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_orders', to='suppliers.supplier', verbose_name='Supplier'),
        ),
    ]
