# Generated by Django 4.0.3 on 2022-03-09 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_stonetype'),
        ('orders', '0009_gravel_stype_historicalgravel_stype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravel',
            name='stype',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='stype',
        ),
        migrations.AddField(
            model_name='gravel',
            name='driver',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='driver',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='gravel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_orders', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalgravel',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
