# Generated by Django 4.0.3 on 2022-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_gravelorder_builder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinspectionmodel',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='inspectionmodel',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='note'),
        ),
    ]
