# Generated by Django 4.0.3 on 2022-03-09 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_stonetype'),
        ('orders', '0010_remove_gravel_stype_remove_historicalgravel_stype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravel',
            name='stype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.stonetype', verbose_name='stone type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='stype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.stonetype', verbose_name='stone type'),
        ),
    ]
