# Generated by Django 4.0.3 on 2022-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_gravel_stype_historicalgravel_stype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Order Complete'),
        ),
        migrations.AddField(
            model_name='historicalgravel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Order Complete'),
        ),
    ]
