# Generated by Django 4.0.3 on 2022-04-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_historicalinspectionmodel_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinspectionmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inspectionmodel',
            name='order',
        ),
        migrations.CreateModel(
            name='ConcreteInspection',
            fields=[
                ('inspectionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.inspectionmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.concreteorder', verbose_name='concrete order')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.inspectionmodel',),
        ),
    ]
