# Generated by Django 4.0.3 on 2022-03-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_gravel_is_complete_historicalgravel_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concrete',
            name='ddate',
        ),
        migrations.RemoveField(
            model_name='concrete',
            name='ndate',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='atot',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='etot',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='qord',
        ),
        migrations.RemoveField(
            model_name='gravel',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='historicalconcrete',
            name='ddate',
        ),
        migrations.RemoveField(
            model_name='historicalconcrete',
            name='ndate',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='atot',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='etot',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='qord',
        ),
        migrations.RemoveField(
            model_name='historicalgravel',
            name='qtype',
        ),
    ]
