# Generated by Django 4.0.3 on 2022-04-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_gravelordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravelordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravel_order_notes', to='orders.gravelorder', verbose_name='gravel order'),
        ),
    ]
