# Generated by Django 4.0.3 on 2022-04-08 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('orders', '0015_alter_gravelordernote_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteorder',
            name='po',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='concreteorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_concrete_orders', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalconcreteorder',
            name='po',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='purchase order'),
        ),
    ]
