# Generated by Django 4.0.3 on 2022-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_sitenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='url'),
        ),
    ]
