# Generated by Django 4.0.3 on 2022-04-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_historicalsitemodel_slug_alter_sitemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenote',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_notes', to='sites.sitemodel', verbose_name='site note'),
        ),
    ]
