# Generated by Django 4.0.3 on 2022-03-13 05:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0004_rename_concretetype_concreteitems_and_more'),
        ('clients', '0003_alter_lot_builder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGravelOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('po', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='Purchase Order')),
                ('priority', models.CharField(max_length=50, verbose_name='priority')),
                ('bsdt', models.CharField(blank=True, max_length=50, null=True, verbose_name='B/S D/T')),
                ('need_by', models.DateField(verbose_name='date needed')),
                ('rloads', models.SmallIntegerField(verbose_name='loads requested')),
                ('dloads', models.SmallIntegerField(default=0, verbose_name='loads delivered')),
                ('ddate', models.DateField(verbose_name='date delivered')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.stonetype', verbose_name='stone type')),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.lot', verbose_name='lot')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical Stone Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[\\S\\w]')], verbose_name='Purchase Order')),
                ('priority', models.CharField(max_length=50, verbose_name='priority')),
                ('bsdt', models.CharField(blank=True, max_length=50, null=True, verbose_name='B/S D/T')),
                ('need_by', models.DateField(verbose_name='date needed')),
                ('rloads', models.SmallIntegerField(verbose_name='loads requested')),
                ('dloads', models.SmallIntegerField(default=0, verbose_name='loads delivered')),
                ('ddate', models.DateField(verbose_name='date delivered')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.stonetype', verbose_name='stone type')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.lot', verbose_name='lot')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Stone Type',
                'verbose_name_plural': 'Stone Types',
                'db_table': 'orders_gravel_stonetypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GravelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date(2022, 3, 13), verbose_name='scheduled on')),
                ('loads', models.SmallIntegerField(default=1, verbose_name='loads')),
                ('ddriver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gravel.gravelorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Gravel Delivery',
                'verbose_name_plural': 'Gravel Deliveries',
                'db_table': 'orders_gravel_deliveries',
                'managed': True,
            },
        ),
    ]
