# Generated by Django 4.0.3 on 2022-03-13 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveldelivery',
            name='sdate',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 5, 34, 3, 648132, tzinfo=utc), verbose_name='scheduled on'),
        ),
    ]
