# Generated by Django 4.0.3 on 2022-03-13 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gravel', '0003_alter_gravelorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveldelivery',
            name='sdate',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 5, 43, 37, 588226, tzinfo=utc), verbose_name='scheduled on'),
        ),
        migrations.AlterField(
            model_name='gravelorder',
            name='ddate',
            field=models.DateField(blank=True, null=True, verbose_name='date delivered'),
        ),
        migrations.AlterField(
            model_name='historicalgravelorder',
            name='ddate',
            field=models.DateField(blank=True, null=True, verbose_name='date delivered'),
        ),
    ]
