# Generated by Django 4.0.3 on 2022-03-13 05:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gravel', '0004_alter_graveldelivery_sdate_alter_gravelorder_ddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveldelivery',
            name='sdate',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 5, 54, 18, 29317, tzinfo=utc), verbose_name='scheduled for'),
        ),
        migrations.CreateModel(
            name='HistoricalGravelDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.datetime(2022, 3, 13, 5, 54, 18, 29317, tzinfo=utc), verbose_name='scheduled for')),
                ('loads', models.SmallIntegerField(default=1, verbose_name='loads')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ddriver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='delivery driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gravel.gravelorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'historical Gravel Delivery',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
