# Generated by Django 4.0.3 on 2022-03-13 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gravel', '0005_alter_graveldelivery_sdate_historicalgraveldelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='graveldelivery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='historicalgraveldelivery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='graveldelivery',
            name='sdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='scheduled for'),
        ),
        migrations.AlterField(
            model_name='historicalgraveldelivery',
            name='sdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='scheduled for'),
        ),
    ]
