name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.4]

    env:
      SECRET_KEY: TESTtheDJANGOapplication
      DEBUG: True
      ROOT_URLCONF: config.urls.local
      DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/jsc
      USER_MODEL: accounts.CustomUser
      STATIC_ROOT: /project/static/

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/tests.txt
    - name: Run Tests
      run: |
        cd project
        python manage.py test
